---
swagger: "2.0"
#add default host - this enables you to test the service direct from swagger editor
#don't forget to add the directive for CORS in the response header to make this
schemes:
  - http
info:
  version: "1.0"
  title: "Hello Adder API"
paths:
  /add/{num1}/{num2}:
    get:
      description: "Adds numbers!"
      operationId: "addNum1Num2GET"
      parameters:
      - name: "num1"
        in: "path"
        description: "num1."
        required: true
        type: "integer"
      - name: "num2"
        in: "path"
        description: "num2."
        required: true
        type: "integer"
      responses:
        '200':
          description: A User object
          schema:
            $ref: '#/definitions/addresult'
      x-swagger-router-controller: "Default"

definitions:
  addresult:
    type: object
    properties:
      result:
        type: integer
        description: The result.