swagger: "2.0"
host: 192.168.0.48:8080
info:
  version: "1.0"
  title: "Hello Adder API"
  
  
paths:
  
  /add/{num1}/{num2}:
    get:
      description: Adds numbers!
      parameters:
        - name: num1
          in: path
          type: integer
          required: true
          description: num1.
        - name: num2
          in: path
          type: integer
          required: true
          description: num2.
      responses:
        '200':
          description: A User object
          schema:
            $ref: '#/definitions/addresult'
                
                
definitions:
  addresult:
    type: object
    properties:
      result:
        type: integer
        description: The result.
      
        